- ChangeLog
- benchcab/run_cable_site.py
- meta.yaml
- setup.cfg
It seems the code was not copying the new pft_params.nml file to the run/ directory so it didn't use the proper information for the vegetation.
Now when comparing 2 science configs with the trunk in modelevaluation.org, we get:
- differences between configs
- NEE not equal 0
See [results](https://modelevaluation.org/analyses/anywhere/fQ89uhxtF5b8yQ4kd/5TqGyBXuRFFMFiBed/WakeWp8Qt97y5s8Do/all)
> Fix #11 issue with canopy height

- benchcab/benchtree.py
- meta.yaml
- setup.cfg
Now the namelists will be sourced from a sub-directory in the work directory instead of CABLE-AUX or the source code. This will allow for changing the base namelists more easily.
> Fix issue 13. Source namelist from a common directory

- ChangeLog
- benchcab/get_cable.py
- meta.yaml
- setup.cfg
- tests/conftest.py
- tests/test_workdir.py
Now we checkout the trunk directly without a copy into a User branch. And there is a revision number added to the config.yaml file. This allows for the selection of a specific version of a branch to test instead of the HEAD.
> Add revision number in branch description

- ChangeLog
- benchcab/bench_config.py
- benchcab/benchsiterun.py
- benchcab/benchtree.py
- benchcab/run_cable_site.py
- meta.yaml
- setup.cfg
This adds 2 things:
- better handling of the revision number per branch. We want to be able to run for a specified revision number or from the HEAD of each branch independently. Now each run of benchcab writes out the revision numbers used in a different file.
- run for a subset of the PLUMBER2 sites. It's now possible to specify sites to run in the config.yaml file under a `met_subset` list. For the moment, one needs to specify the exact filenames, it will need to be changed to specifying the site name instead and the code figuring out the filename for each site.
> Handling of revision number and a subset of met. sites

- tests/common.py
- tests/test_benchtree.py
- tests/test_task.py
Previously, `pytest` fails if the command is not run from the project root directory. This change uses the `TMPDIR` environment variable instead of `Path.cwd()` so that `pytest` runs correctly from any directory.
Using `TMPDIR` has the added benefit that we won't run into permission issues if we run the tests on a central installation of `benchcab`.
Fixes #26
> Use `TMPDIR` environment variable instead of CWD

- benchcab/bench_config.py
- benchcab/benchcab.py
- benchcab/benchsiterun.py
- benchcab/internal.py
- benchcab/task.py
- tests/common.py
- tests/test_bench_config.py
These changes allow users to run a set of standard tests (experiments) for CABLE from which model output can be piped into [modelevaluation.org](modelevaluation.org). In particular we
- no longer default to running CABLE with all met files in the FLUXNET dataset.
- now use preset experiments that enforce which met sites are to be used. These are defined in the NRI Land testing workspace on [modelevaluation.org](modelevaluation.org).
This addresses issues #10 and #25.
> Add me.org met site configurations

- benchcab/get_cable.py
The use of `|` was introduced in python 3.10.
We do this so that benchcab is compatible with the version of python installed on analysis3 conda environment on NCI (python 3.9).
Fixes #30
> Use `typing.Union` to support python < v3.10

- benchcab/task.py
- tests/test_task.py
Currently the `patch` method in the [f90nml](https://github.com/marshallward/f90nml) package does not preserve existing derived type parameters when a derived type patch is applied.
This change allows for existing derived type parameters to be preserved when adjusting the namelist file for each task.
Update unit tests for `adjust_namelist_file()` to test existing namelist parameters are preserved.
> Add support for patching derived types

- benchcab/bench_config.py
- benchcab/task.py
- tests/common.py
- tests/test_bench_config.py
- tests/test_benchtree.py
- tests/test_task.py
This change allows for users to add branch specific namelist settings in the config file that get "patched" to the base namelist settings used for both branches. These additional settings are set by specifying an optional `patch` key in each realisation. Currently, this change supports the ability to add a `patch` to both realisations.
Addresses issue https://github.com/CABLE-LSM/benchcab/issues/29
> Add branch specific namelist settings 

- benchcab/internal.py
- benchcab/task.py
- tests/test_task.py
Specify `cable` in the top level of each science config dictionary. This is consistent with how branch specific namelist patches are specified in the config file.
Fixes #46
> Specify namelist name in science configurations

- .github/actions/build/action.yml
- .github/workflows/build_and_preview.yml
- .github/workflows/build_and_publish.yml
- .gitignore
- mkdocs-requirements.txt
Fix #45 . 
The publishing workflow from master branch has worked on my own personal branch:
- published site: https://ccarouge.github.io/benchcab/
- actions summary: https://github.com/ccarouge/benchcab/actions 
The publishing workflow for a preview has worked in this PR.
> fix #45: Github actions to publish on Pages

- tests/conftest.py
- tests/test_bench_config.py
- tests/test_benchtree.py
- tests/test_task.py
We should always use `TMP_DIR` so that when tests fail, all files are cleaned up.
This change allows all tests to use the same setup/teardown pytest fixture.
Fixes https://github.com/CABLE-LSM/benchcab/issues/41
> Use TMP_DIR when reading and writing files

- benchcab/get_cable.py
- benchcab/job_script.py
- Add `text=True` to subprocess.run() arguments so that captured output is formatted as a string.
- Replace the `shlex` module by adding the `shell=True` argument.
- Replace `subprocess.call` with `subprocess.run` as this is recommended for most use cases. Use the built in `subprocess.CalledProcessError` exception type for error handling.
Note, code related to building CABLE is left untouched (this will likely be refactored in a later PR).
Fixes #39
> Polish `subprocess` calls

- benchcab/__init__.py
- benchcab/benchcab.py
- meta.yaml
Currently the version is hard coded in both `setup.cfg` and `meta.yaml`. Ideally, we want the version number to be defined in a single place in the code base. This change defines the `setup.cfg` file to be the single source of truth for the version number.
Use `importlib` to obtain the version number from `setup.cfg` and store in the `__version__` dunder variable in `benchcab/__init__.py`.
Add a `--version` command line flag to `benchcab` which prints the version number to stdout.
Use Jinja2 templating with `load_setup_py_data()` to render the version number in `meta.yaml`. See [conda docs] for details.
The following commands have been tested:
- `pip install --user .` success.
- `conda build -c conda-forge .` success.
- `benchcab -f` success.
Fixes …
> Add version flag

- docs/user_guide/config_options.md
- docs/user_guide/default_science_configurations.md
- docs/user_guide/expected_output.md
- docs/user_guide/index.md
- mkdocs.yml
The changes to the documentation include:
- change options descriptions
- use of sub-commands instead of command line options.
- add expected stdout 
- modify some formatting in the user guide
- move the default science configurations to their own page to improve visibility
The documentation still needs some documentation to use me.org but it is better to move that to its own ticket I think.
> #70: update doc

- benchcab/bench_config.py
- benchcab/benchcab.py
- benchcab/get_cable.py
- benchcab/job_script.py
- docs/user_guide/config_options.md
- tests/common.py
- tests/test_bench_config.py
The user should be able to checkout branches of other users so that test suites can be reproduced by any user.
This change lets the user specify the path relative to the SVN root of the CABLE repository for each branch by specifying the `path` key in the configuration file. Remove the `trunk` and `share_branch` keys from the configuration file as this information is contained within `path`.
This change repurposes the `name` key for each branch to be an alias used internally by benchcab. This lets the user specify the directory name when checking out the branch, that is, `name` is the optional `PATH` argument to svn checkout`. This is useful in the case that we have a collision in branch names when checking out multiple branches.
Remove the `-M` PBS argument for sending emails in the job …
> Add ability to use branches of other users

- benchcab/benchcab.py
- benchcab/utils/pbs.py
- tests/test_benchcab.py
- tests/test_pbs.py
This change specifies the absolute path to the benchcab executable in the job script so that we don't run into path issues when running using a 'locally installed' version of benchcab. This will be helpful making code changes and testing them on NCI.
Fixes #95
> Specify absolute path to benchcab executable

- benchcab/benchcab.py
- benchcab/cli.py
- tests/test_cli.py
This change adds a subcommand `fluxsite-submit-job` that writes the PBS job to the file system and then submits the job to the queue. This allows us to run the full fluxsite test by executing each step separately, i.e. `benchcab checkout && benchcab build && benchcab fluxsite-setup-work-dir && benchcab fluxsite-submit-job`.
Fixes #109
> Add job script submission and generation step

- benchcab/repository.py
- benchcab/task.py
- benchcab/utils/os.py
- tests/test_task.py
Currently, the CABLE executable is run from the current working directory instead of the task directory by using the absolute path to the executable. However, we should be running the executable from the task directory (otherwise CABLE will complain it cannot find the soil and PFT namelist files). This was a bug that was introduced in #99.
This change makes it so we change into the task directory before running the CABLE executable.
Fixes #123
> Run executable from task dir

- benchcab/bench_config.py
- benchcab/benchcab.py
- benchcab/comparison.py
- benchcab/internal.py
- benchcab/task.py
- benchcab/utils/pbs.py
- docs/user_guide/config_options.md
- tests/common.py
- tests/test_bench_config.py
- tests/test_pbs.py
This change promotes PBS related constants to optional parameters in the configuration file so that PBS flags can be set at runtime.
This is useful in running multiple benchcab instances with different job parameters such as memory and the number of CPUs. This will also allow us to easily find an optimal number of CPUs to use to maximise performance.
This change also adds the ability to switch on and off multiprocessing at runtime via an optional parameter in the config file.
Fixes #104
> Promote PBS constants to optional parameters

- benchcab/config.py
- benchcab/fluxsite.py
- benchcab/repository.py
- docs/user_guide/config_options.md
- tests/common.py
- tests/test_config.py
- tests/test_fluxsite.py
Currently, `benchcab` does not support removing namelist parameters from the base namelist file. For example, legacy CABLE branches may not be compatible with a namelist parameter in the base namelist file.
This change adds a `patch_remove` key which will remove a given set of namelist parameters for a specific branch.
Fixes #92
> Add patch remove feature

- benchcab/internal.py
- docs/user_guide/config_options.md
- docs/user_guide/index.md
Fixes the following errors:
Fixes #131
> Fix documentation errors

- docs/user_guide/config_options.md
Modifications to `config_options.md` in the documentation to improve readability:
- Remove redundant level of heading
- add a link to sub-headings
- replace headings for innermost options with links
- State default values first in the description
- Reorder options to keep the simpler, required options first
- Add code example for every single option
- Add tooltips in examples where useful
> #140 - Alternate config_options style

- .conda/benchcab-dev.yaml
Possibly the largest commit of the day.
> Removed numpy from benchcab-dev.yaml. Fixes #160

- benchcab/fluxsite.py
- tests/test_fluxsite.py
> Add benchcab version to model output attributes

- benchcab/benchcab.py
- benchcab/cli.py
- benchcab/comparison.py
- benchcab/config.py
- benchcab/environment_modules.py
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/repository.py
- benchcab/utils/fs.py
- benchcab/utils/pbs.py
- benchcab/utils/subprocess.py
- benchcab/workdir.py
- ruff.toml
- tests/common.py
- tests/conftest.py
- tests/test_benchcab.py
- tests/test_cli.py
- tests/test_comparison.py
- tests/test_config.py
- tests/test_fluxsite.py
- tests/test_fs.py
- tests/test_pbs.py
- tests/test_repository.py
- tests/test_subprocess.py
- tests/test_workdir.py
This change fixes minor linter warnings from the Ruff linter and adds a basic `ruff.toml` configuration.
Fixes #145
> Switch linting to Ruff

- benchcab/benchcab.py
- benchcab/comparison.py
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/utils/fs.py
- benchcab/workdir.py
- tests/test_benchcab.py
- tests/test_comparison.py
- tests/test_fluxsite.py
- tests/test_fs.py
- tests/test_workdir.py
Fixes #150
Added a `mkdir()` wrapper to use throughout the code:
- `benchcab` to create `src/`, hence removing the `setup_src_dir()` function.
- `fluxsite` to create the task directories within `setup_task()`
- `workdir` to create the fluxsite run directory tree.
Defined `FLUXSITE_DIRS`: a dictionary in `internal.py` that contains all the individual directories for the fluxsite runs.
Change the creation and deletion of fluxsite directory tree and source directory to use relative paths instead of absolute paths.
> Refactor work_dir creation

- benchcab/comparison.py
- benchcab/fluxsite.py
We currently do not exit with non-zero if an uncaught exception occurs within a multiprocessing child process.
`multiprocessing.Pool.map()` will kill all processes if any one process throws an exception and then re-raise that exception in the parent process.
Fixes #122
> Use `multiprocessing.Pool.map()` for parallelism

- benchcab/benchcab.py
> Fix indexing of pbs key in config

- benchcab/utils/pbs.py
- tests/test_pbs.py
The PBS job script produces a lot of excessive output from the `module purge` and `module load <module>` commands. This can be fixed easily by enabling the set options after the module commands.
Replace xtrace mode `-x` with verbose mode `-v` as the job script is not complex.
Fixes #174
> Update usage of `set -ex`

- benchcab/benchcab.py
- benchcab/cli.py
- tests/test_cli.py
> Add config validation CLI

- benchcab/fluxsite.py
- benchcab/model.py
- tests/test_model.py
This change removes any hard coded paths to the built executable that are outside the `CableRepository` class and replaces these with a method that returns the path to the executable. This is done to prepare for the changes in #183 which requires paths to vary accross different `CableRepository` objects.
Fixes #199
> Add getter method for built executable

- COPYRIGHT.txt
- LICENSE
- README.md
- benchcab/__init__.py
- benchcab/benchcab.py
- benchcab/cli.py
- benchcab/comparison.py
- benchcab/config.py
- benchcab/environment_modules.py
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/model.py
- benchcab/utils/__init__.py
- benchcab/utils/fs.py
- benchcab/utils/pbs.py
- benchcab/utils/subprocess.py
- benchcab/workdir.py
- docs/index.md
- docs/user_guide/index.md
- mkdocs.yml
Fixes #118 and #108
- Add license and copyright files. 
- Add copyright notice to all the files and the documentation footer to follow [best practices](https://github.com/ACCESS-NRI/template/blob/main/README.md)
- Add license mention on documentation home page
- Direct help request to GitHub or forum user support.
- Add license badge in README
> License and branding

- .conda/benchcab-dev.yaml
- .conda/meta.yaml
- benchcab/benchcab.py
- benchcab/data/config-schema.yml
- benchcab/data/test/config-valid.yml
- benchcab/data/test/integration.sh
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/model.py
- benchcab/utils/repo.py
- docs/user_guide/config_options.md
- tests/test_fluxsite.py
- tests/test_model.py
Currently benchcab can only fetch repositories from the subversion repository. This change adds the ability to specify and checkout repositories from GitHub so that benchcab can be used when CABLE moves over to Git.
Fixes #183, #197
> Add support for checking out GitHub repositories

- docs/user_guide/config_options.md
Fixes #195
Now uses links from `benchcab-evaluation` workspace in modelevaluation.org so everyone can reach them.
Test: pages are now accessible when logged out of me.org
> Update links to experiment pages in documentation

- benchcab/benchcab.py
- benchcab/data/config-schema.yml
- benchcab/data/test/config-invalid.yml
- benchcab/data/test/config-valid.yml
- benchcab/data/test/integration.sh
- benchcab/internal.py
- docs/user_guide/config_options.md
The `experiment` key in the config file is specific to fluxsite tests. This key is better placed under the `fluxsite` key as we will soon have the ability to run spatial only tests.
This change moves the `experiment` key under the `fluxsite` key and sets the experiment key to be optional.
Fixes #192
> Move `experiment` key under `fluxsite`

- README.md
- docs/index.md
- mkdocs.yml
Content is duplicated across `docs/index.md` and `README.md`. This change merges the two pages and embeds the README contents in index.md.
Fixes #218
> Include README contents in index.md

- benchcab/benchcab.py
- benchcab/comparison.py
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/model.py
- benchcab/utils/fs.py
- tests/test_comparison.py
- tests/test_fluxsite.py
- tests/test_fs.py
- tests/test_model.py
This change forces paths to be relative to the CWD throughout the code base unless absolute paths are required.
Improves code readability and cleaner logging to standard output.
Fixes #162
> Remove absolute paths from logged standard output

- tests/conftest.py
- tests/test_comparison.py
- tests/test_fluxsite.py
- tests/test_fs.py
- tests/test_model.py
This change removes any assertions on standard output from the tests so that tests focus on testing functionality (where possible) rather than the messages (print statements) that are emitted from the tested functions.
Fixes #221
> Remove tests on standard output

- benchcab/data/test/integration.sh
- benchcab/model.py
- tests/test_model.py
The `serial_cable` and `parallel_cable` scripts were deprecated in https://github.com/CABLE-LSM/CABLE/pull/193. This change does the same in the benchcab source code.
Code branches that require the serial_cable and parallel_cable scripts can use the `build_script` key as a work around.
Fixes #223
> Deprecate serial_cable and parallel_cable scripts

- .conda/meta.yaml
- setup.cfg
- setup.py
[PBR](https://docs.openstack.org/pbr/latest/index.html) is removed from the build dependencies so that we can use [versioneer](https://github.com/python-versioneer/python-versioneer) to solve #129. This change removes the [additional options provided by PBR in setup.cfg](https://docs.openstack.org/pbr/latest/user/using.html#setup-cfg) or replaces these options with [the default options that come with setuptools](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html).
Fixes #227
> Deprecate PBR build dependency

- setup.cfg
- setup.py
- versioneer.py
Previously (prior to #228), we used the [PBR][PBR] package with an explicit version number in setup.cfg. This enables the 'pre-versioning' mode of managing version strings (see [features][PBR-versioning]) which raises an error if the inferred version from Git tags is greater than explicit version in setup.cfg. This prevents developers from doing an editable install via `pip install -e .` (see #129). This issue was fixed implicitly in #228 when PBR was removed from the build dependencies.
This change is a feature in that it implements dynamic version strings from Git tags via [versioneer][versioneer] so that an explicit version number in setup.cfg is not required. We choose [versioneer][versioneer] so that version strings were consistent across `pip` and `conda` installations. This was not …
> Replace explicit version number with versioneer

- benchcab/benchcab.py
- benchcab/data/test/integration.sh
- benchcab/fluxsite.py
- benchcab/internal.py
- benchcab/utils/pbs.py
- tests/test_fluxsite.py
- tests/test_pbs.py
Fixes #230 
**Merge Message**
When running benchcab, it checks out on svn branch, potentially for data files like `GRID_DATA`. This commit:
- Removes the dependency to check out in svn branch
- Cleans up internal variables for unused files
- Uses alternative sources for existing data files in svn - testing was done via bitwise comparison generated by `main` vs `230-remove-svn-dependency` branch during integration tests
> Remove svn dependency in default runs

- benchcab/benchcab.py
- benchcab/config.py
- benchcab/data/config-schema.yml
- benchcab/data/test/config-basic.yml
- benchcab/data/test/config-invalid.yml
- benchcab/data/test/config-optional.yml
- benchcab/internal.py
- docs/user_guide/config_options.md
- docs/user_guide/index.md
- tests/test_benchcab.py
- tests/test_config.py
Fixes #231 , #246
**Merge Message**
- In case the user provides the `project` keyword, use the corresponding value as ID, otherwise use `$PROJECT`.
- Added skippable tests for validating against existing project groups. 
- Modularized test cases for `config` module.
> `project` keyword improvements in `config.yml`

- benchcab/benchcab.py
- benchcab/internal.py
Resolves #220 
**Merge Message**
`analysis3-unstable` had a package named `ld` whose library search paths were different from system's `ld` (`/usr/bin/ld`). This commit ensures that during compilation process, any binaries would be searched in system paths first before `conda` paths.
Tested with CABLE commit `67a52dc5721f0da78ee7d61798c0e8a804dcaaeb`
**Environment:** Cloned `analysis3-unstable` and remove `benchcab`.
> Prioritize system binaries over paths set by user

- benchcab/utils/fs.py
- tests/test_fs.py
Resolves #161 
**Merge Message**
- Add `DEBUG` log message when changing current working directory.
- Add unit test for `chdir` functionality, where it only changes directory within context.
> Add logging and tests for `chdir`

- .conda/benchcab-dev.yaml
- .conda/meta.yaml
Set minimum payu version to [1.0.30 (CABLE model driver support)](https://github.com/payu-org/payu/releases/tag/1.0.30).
Fixes #261
> Set minimum payu version to 1.0.30

- .conda/benchcab-dev.yaml
- .conda/meta.yaml
> Add jinja2 to dependencies

- .github/workflows/ci.yaml
This change improves the CI to detect missing dependencies in meta.yaml by running pytest with the dependencies that come installed with a local benchcab install.
This PR should go in after #266 so we can verify the CI is working as intended.
Fixes #264
> Run pytest using local conda installation

- setup.cfg
Currently the uploaded tarball for benchcab v4.0.0 is missing the site-packages/benchcab/data directory (see https://anaconda.org/accessnri/benchcab/files). This change fixes this by replacing the `include_package_data` option with the `package_data` option in setup.cfg (see [Data Files Support](https://setuptools.pypa.io/en/latest/userguide/datafiles.html)).
Conda package deployment was tested [here](https://github.com/SeanBryan51/benchcab/actions/runs/8353675085/job/22865775572) in a forked repository and the uploaded tarball contains the package data directory.
Fixes #267
> Use package_data configuration option

- benchcab/data/config-schema.yml
- benchcab/model.py
- docs/user_guide/config_options.md
Currently benchcab assumes the compiled executables are installed under the src/offline directory, however this may not always be the case (e.g. [this script](https://github.com/CABLE-LSM/CABLE/blob/main/build.bash) installs binaries under `<project_root>/bin`). This change adds the `install_dir` option which lets the user specify the directory in which benchcab can find the built executables.
Fixes #259
> Add install_dir option

- docs/user_guide/running_CABLE_v2.md
- src/benchcab/benchcab.py
- src/benchcab/data/test/integration.sh
- src/benchcab/internal.py
- src/benchcab/model.py
- src/benchcab/utils/fs.py
- tests/test_fluxsite.py
- tests/test_fs.py
- tests/test_model.py
- tests/test_spatial.py
The CABLE build system was transitioned from Makefile to CMake: see https://github.com/CABLE-LSM/CABLE/pull/216, https://github.com/CABLE-LSM/CABLE/pull/200. This change adds support for building CABLE via CMake in benchcab so that CABLE versions which branch from the HEAD of main can be tested.
Closes #258
> Update to CMake build

- src/benchcab/model.py
CABLE is linked against incorrect libraries for netcdf and MPI when running benchcab (v4.0.2) from the hh5 conda environment. The issue is due to environment variables being set which affect the behaviour of the build, notably LDFLAGS and CMAKE_PREFIX_PATH, which point CMake to find the netcdf and MPI libraries installed in the current conda environment. This change unsets these variables so that CMake finds the appropriate libraries which get loaded in as modules.
Fixes #279
> Unset LDFLAGS and CMAKE_PREFIX_PATH variables

- docs/user_guide/index.md
This change adds a quick-start section to the user guide so that users have all the instructions needed to run benchcab on Gadi without having to read the full explanation of each step in the documentation.
Fixes #277
> Add quick-start instructions

- src/benchcab/benchcab.py
- src/benchcab/main.py
Running benchcab without the `-v` flag is still providing `DEBUG` log output when we should only output `INFO` log output. This is because `get_logger()` is being called for the first time here:
https://github.com/CABLE-LSM/benchcab/blob/94824588d92727aa396acf0298166dc00eacb341/benchcab/benchcab.py#L60
Instead of here:
https://github.com/CABLE-LSM/benchcab/blob/94824588d92727aa396acf0298166dc00eacb341/benchcab/main.py#L26
This change instantiates the logger in `main.py` and sets the logger object in the Benchcab application object so that the correct debug level is used.
Fixes #280
> Set logger in Benchcab object

- src/benchcab/utils/repo.py
Currently, the `GitRepo` and `SVNRepo` objects incorrectly modify the path to the source repository if the path points to a directory initialised by either `git` or `svn`. This change adds checks on the repository path so that the correct behaviour applies in this case.
Fixes #243
> Check if repository_path is already initialized

- docs/user_guide/config_options.md
> Update outdated configuration options in documentation

- src/benchcab/benchcab.py
- src/benchcab/utils/__init__.py
- src/benchcab/utils/subprocess.py
> Propagate verbose flag into PBS job script

- src/benchcab/benchcab.py
- src/benchcab/comparison.py
- src/benchcab/fluxsite.py
- src/benchcab/internal.py
- src/benchcab/utils/state.py
- src/benchcab/workdir.py
- tests/test_comparison.py
- tests/test_fluxsite.py
- tests/test_state.py
- tests/test_workdir.py
This change improves how the exit status of fluxsite tasks and bitwise comparison tasks are reported in the PBS log files so that users know which tasks succeeded/failed.
A `State` object is introduced as a minimal way of having state persist between separate processes. This is necessary for correctly showing the status of fluxsite and comparison runs as these tasks are run inside child processes which do not share the same data structures in the parent process.
Fixes #180
> Log status of fluxsite and comparison runs

- docs/user_guide/config_options.md
Add explanations in the documentation about specifying namelist options with boolean values in config.yaml since they need to be supplied with Python syntax and not Fortran syntax.
> Booleans in patch and science_configurations in config.yaml

- src/benchcab/model.py
- tests/test_model.py
Benchcab currently fails to install the executables for https://github.com/CABLE-LSM/CABLE/pull/469 due to a change in the structure of the CMakeLists.txt file - namely a single executable is now only built per build tree where as before both serial and MPI executables were built under the same build tree. Whilst this was convenient, it breaks the CMake model of one build configuration per build tree (see PR for more details) and will be hard to maintain with MPI development going forward.
This change adds support for the changes to CMakeLists.txt as part of https://github.com/CABLE-LSM/CABLE/pull/469 by generating two out of source builds for serial and MPI applications instead of one. This change is also backwards compatible for CABLE commits prior to the changes to CMakeLists.txt.
> Build MPI and serial executables in separate build trees

- docs/user_guide/use_cases.md
- mkdocs.yml
Documentation change only.
Add some examples of config.yaml for various cases. This intends to showcase the use of various options. It is also a way to simplify the setup by CABLE users allowing to copy/paste fuller configuration files than what is in `bench_example`.
> config examples for various use cases

- .conda/benchcab-dev.yaml
- .conda/meta.yaml
Minimum required version for `meorg_client` to get access to recent updates.
> Updated minimum meorg_client version required. Fixes #321

- src/benchcab/benchcab.py
- src/benchcab/data/pbs_jobscript.j2
- src/benchcab/data/test/pbs_jobscript_default.sh
- src/benchcab/data/test/pbs_jobscript_no_skip_codecov.sh
- src/benchcab/data/test/pbs_jobscript_skip_optional.sh
- src/benchcab/data/test/pbs_jobscript_verbose.sh
- src/benchcab/utils/pbs.py
- tests/test_pbs.py
Loading modules prior to launching benchcab may break the environment (as evident in #329 for the xp65 container environments).
Modules do not actually need to be loaded when running CABLE as CMake sets the RPATH on the executable to point to all the library dependencies, so it is safe to remove these module statements from the job script.
Fixes #329
> Remove module load/purge statements from PBS job
